Repository projet-d-innovation/delib-backend, pull requests merged in 2023-06, with the labels that each got.

#76 Session universitaire update
  session-universitaire-service/pom.xml
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/constant/CoreConstants.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/controller/SessionUniversitaireController.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/exception/DuplicateEntryException.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/exception/InternalErrorException.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/exception/handler/GlobalExceptionHandler.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/exception/handler/dto/ExceptionResponse.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/model/AbstractEntity.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/model/SessionUniversitaire.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/service/SessionUniversitaireService.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/service/SessionUniversitaireServiceImpl.java
  session-universitaire-service/src/main/resources/messages/messages.properties
Labels: enhancement

#77 Utilisateur service - Fix departementCodes null values issue
  utilisateur-service/src/main/java/ma/enset/utilisateur/service/UtilisateurServiceImpl.java
Labels: enhancement

#81 change deliberations module name
  deliberation-service/pom.xml
Labels: bug

#83 Inscription pedagogique
  .idea/dataSources.xml
  gateway-server/src/main/java/ma/enset/gateway/GatewayApplication.java
  gateway-server/src/main/resources/application.yml
  inscription-pedagogique-service/pom.xml
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/InscriptionPedagogiqueApplication.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/client/FiliereClient.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/client/SessionUniversitaireClient.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/client/UtilisateurClient.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/client/WebClientConfig.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/config/CorsConfiguration.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/config/ValidationConfig.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/constant/CoreConstants.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/controller/EtudiantController.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/controller/InscriptionPedagogiqueController.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/EtudiantResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/InscriptionCreationRequest.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/InscriptionPagingResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/InscriptionResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/InscriptionUpdateRequest.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/RequiredSearchParams.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/ApiClientException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/BusinessException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/DuplicateEntryException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/ElementAlreadyExistsException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/ElementNotFoundException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/InternalErrorException.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/handler/GlobalExceptionHandler.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/exception/handler/dto/ExceptionResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/mapper/InscriptionPedagogiqueMapper.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/model/AbstractEntity.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/model/EtatInscriptionPedagogique.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/model/InscriptionPedagogique.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/repository/InscriptionPedagogiqueRepository.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/EtudiantService.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/EtudiantServiceImpl.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/InscriptionPedagogiqueService.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/InscriptionPedagogiqueServiceImpl.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/validationgroups/OnBulkUpdate.java
  inscription-pedagogique-service/src/main/resources/application.yml
  inscription-pedagogique-service/src/main/resources/messages/messages.properties
  pom.xml
Labels: enhancement

#84 EtudiantResponse : change `dateNaissance` type to `Date`
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/EtudiantResponse.java
Labels: fix

#90 Fix cors configuration properties
  gateway-server/src/main/resources/application.yml
Labels: fix

#92 include `filiere` in `semestre response`
  filiere-service/src/main/java/ma/enset/filiereservice/contoller/FiliereController.java
  semestre-service/src/main/java/ma/enset/semestreservice/client/FiliereClient.java
  semestre-service/src/main/java/ma/enset/semestreservice/controller/SemestreController.java
  semestre-service/src/main/java/ma/enset/semestreservice/dto/FiliereResponse.java
  semestre-service/src/main/java/ma/enset/semestreservice/dto/SemestreResponse.java
  semestre-service/src/main/java/ma/enset/semestreservice/service/SemestreService.java
  semestre-service/src/main/java/ma/enset/semestreservice/service/SemestreServiceImpl.java
Labels: enhancement

#94 fix `PagingResponse` && `module` includes `semestre`
  deliberation-service/src/main/java/ma/enset/deliberationservice/dto/session/SessionPagingResponse.java
  deliberation-service/src/main/java/ma/enset/deliberationservice/mapper/SessionMapper.java
  departement-service/src/main/java/ma/enset/departementservice/dto/DepartementPagingResponse.java
  departement-service/src/main/java/ma/enset/departementservice/mapper/DepartementMapper.java
  element-service/src/main/java/ma/enset/element/dto/ElementPagingResponse.java
  element-service/src/main/java/ma/enset/element/mapper/ElementMapper.java
  filiere-service/src/main/java/ma/enset/filiereservice/dto/FilierePagingResponse.java
  filiere-service/src/main/java/ma/enset/filiereservice/dto/RegleDeCalculPagingResponse.java
  filiere-service/src/main/java/ma/enset/filiereservice/mapper/FiliereMapper.java
  filiere-service/src/main/java/ma/enset/filiereservice/mapper/RegleDeCalculMapper.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/InscriptionPagingResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/mapper/InscriptionPedagogiqueMapper.java
  module-service/src/main/java/ma/enset/moduleservice/client/SemestreClient.java
  module-service/src/main/java/ma/enset/moduleservice/controller/ModuleController.java
  module-service/src/main/java/ma/enset/moduleservice/dto/ModulePagingResponse.java
  module-service/src/main/java/ma/enset/moduleservice/dto/ModuleResponse.java
  module-service/src/main/java/ma/enset/moduleservice/dto/SemestreResponse.java
  module-service/src/main/java/ma/enset/moduleservice/mapper/ModuleMapper.java
  module-service/src/main/java/ma/enset/moduleservice/service/ModuleService.java
  module-service/src/main/java/ma/enset/moduleservice/service/ModuleServiceImpl.java
  semestre-service/src/main/java/ma/enset/semestreservice/controller/SemestreController.java
  semestre-service/src/main/java/ma/enset/semestreservice/dto/SemestrePagingResponse.java
  semestre-service/src/main/java/ma/enset/semestreservice/mapper/SemestreMapper.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/dto/SessionPagingResponse.java
  session-universitaire-service/src/main/java/ma/enset/sessionuniversitaireservice/mapper/SessionUniversitaireMapper.java
  utilisateur-service/src/main/java/ma/enset/utilisateur/dto/PagingResponse.java
  utilisateur-service/src/main/java/ma/enset/utilisateur/mapper/PermissionMapper.java
  utilisateur-service/src/main/java/ma/enset/utilisateur/mapper/RoleMapper.java
  utilisateur-service/src/main/java/ma/enset/utilisateur/mapper/UtilisateurMapper.java
Labels: enhancement

#95 include all inscrptions in EtudiantResponse get request
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/controller/EtudiantController.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/dto/EtudiantResponse.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/EtudiantService.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/EtudiantServiceImpl.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/InscriptionPedagogiqueService.java
  inscription-pedagogique-service/src/main/java/ma/enset/inscriptionpedagogique/service/InscriptionPedagogiqueServiceImpl.java
Labels: enhancement

#96 fix notes grouping
  note-service/src/main/java/ma/enset/noteservice/service/NoteModuleServiceImpl.java
Labels: fix
